### PR TITLE
included ldap login support for webadmin

### PR DESCRIPTION
**Pull request by tylerwinfield**
updated installation script to install ldap module for php
added support for ldap logins to webadmin
redesigned lookup process to improve security

### CODE REVIEW

**Comment by duel007** [comment]
@nicolasbrechet @jamf 

It seems that @ChrOst has made the changes requested by @jamf here: https://github.com/jamf/NetSUS/pull/14#issuecomment-60817493

Thoughts on a merge? Would be wonderful.

**Comment by StevenStrand** [comment]
There are currently some merge conflicts but upon resolution of these conflicts we will merge.

**Comment by cvgs** [comment]
Why not verify the user against the JSS API? Then you would not have to re-enter all the LDAP information?

**Comment by ChrOst** [comment]
@cvgs and what do you find a valid login if you run multiple sites with different AdminGroups?

**Comment by cvgs** [comment]
@ChrOst You would have to not only check the login credentials, but also evaluate the user’s granular permissions and then "hijack" an existing permission for indirect verification.
Like when the user is allowed to create/update/delete "Software Update Servers" (or "Policies", or "Configurations" - the idea is to pick something that is equally powerful or destructive as managing the NetSUS), he probably should also be allowed to configure the NetSUS. And the JSS API might be accessible in more setups than an LDAP server (e.g. it is even active on an Limited JSS) and could be queried via the Internet, if the setup is designed for this.
But that was just a thought in the back of my head; i'm sure LDAP is also fine. This would just be a nice close integration of the appliance and the rest of the JSS.

**Comment by StevenStrand** [comment]
This has been implemented with the new UI.

**Comment by jelockwood** [comment]
@StevenStrand 
I have just upgraded to NetSUS 5.0 which is supposed to include this new LDAP support. However the webadmin user interface is still only showing Active Directory options and no LDAP options.

What am I missing? I am running NetSUS 5.0 on Ubuntu 16.04.

screen shot 2018-10-01 at 10 40 27

**Pull request closed without merging**
