### PR TITLE
#81 Enable macOS Sierra update sync / catalog

### PR DESCRIPTION
**Pull request by brennanma**
Add Sierra catalog to reposadocommon.py to enable Sierra catalog download.

### CODE REVIEW

**Comment by mrbadluck** [comment]
Will this be merged in the near future?

**Comment by Jamyn** [comment]
Looks good to me. The last real commit was October 2016. I wonder why JAMF is ignoring this pull request, especially since it fixes an issue with 10.12.

**Comment by macmule** [comment]
Hi folks, please review the 4.2.1 release & advise if this PR is still needed.

**Comment by brennanma** [comment]
No, this doesn't appear to be needed any longer.

**Pull request closed without merging**
