### PR TITLE
Update Reposado Library

### PR DESCRIPTION
**Pull request by BadStreff**
Updated the reposado library so that we have the latest catalog URLs. I was unable to find any tests to run to verify correctness but in my internal testing everything has been working normally.

### CODE REVIEW

**Comment by Jamyn** [comment]
They ignored https://github.com/jamf/NetSUS/pull/83/commits for Sierra URLs, and that was submitted in January. I'm really surprised at the level of negligence here. They should add additional project maintainers so users don't wait this long for trivial fixes.

**Comment by DRN88** [comment]
+1

**Comment by brennanma** [comment]
I just sent an email to my account manager at JAMF asked WTF is going on. I'm a bit perturbed that this isn't being updated -- especially given that community members are really doing all the work for them anyway.

**Comment by StevenStrand** [comment]
NetSUS is an open source product and is no longer owned by JAMF.  I will find some time here to see if I can get these pull requests looked through here soon.  I apologize for the long time away.

**Comment by BadStreff** [comment]
@StevenStrand Glad these are going to get looked into! It looks like there is a lot of community interest still in the project - I think it was mentioned in another pull requests but would it be possible to get some members added as contributors?

**Comment by Jamyn** [comment]
I'd be willing to help review.

**Comment by macmule** [comment]
Hi folks, please review the 4.2.1 release & advise if this PR is still needed.

**Comment by BadStreff** [comment]
I don't think this PR is needed any longer and can be closed.

**Comment by macmule** [comment]
Thanks @BadStreff!

**Pull request closed without merging**
