### PR TITLE
Better to use parentheses for print

### LINKED ISSUE #127: Unable to read NBImageInfo.plist. Edit the Image to correct this issue
Having an issue in the latest NetSUS release, image created from latest Mojave Installer using AutoDMG then Imagr. I also tried making the image with DeployStudio which didn't work either.

System Info:
 - Ubuntu 18.04.2 LTS
 - NetSUS v5.0

Inside the NBI:
```
user@host:/srv/NetBoot/NetBootSP0/10.14.3AutoImagrNBI.nbi$ file NBImageInfo.plist
NBImageInfo.plist: XML 1.0 document, ASCII text

user@host:/srv/NetBoot/NetBootSP0/10.14.3AutoImagrNBI.nbi$ ll
total 11764804
drwxrwxrwx 3 smbuser users        4096 Feb 17 07:39 ./
drwxr-xr-x 3 smbuser root         4096 Feb 17 07:48 ../
-rwxrwxrwx 1 smbuser users        2059 Feb 17 07:39 NBImageInfo.plist*
-rwxrwxrwx 1 smbuser users 12047138816 Feb 17 07:39 NetBoot.dmg*
drwxrwxrwx 4 smbuser users        4096 Feb 17 07:39 i386/
```

Stuck on message "Unable to read NBImageInfo.plist. Edit the Image to correct this issue" however, editing the image via webUI does not seem to do anything at all. The file exists with appropriate permissions 
 - I have ran `chmod -R 777 10.14.3AutoImagrNBI.nbi` which did not resolve the problem
 - I have tried `plutil -convert xml1 ./NBImageInfo.plist` (ran on MacOS) which shouldn't & didn't  have any effect either, as the file was already XML format.

image

Editing the image as suggested, seems to have no effect (Still stuck saying the same error):

image

Not sure what else to try. 

Please let me know if there is any other info required or troubleshooting steps that I can take.

Thanks

### PR DESCRIPTION
**Pull request by nmors**
Fixes #127

Parentheses for print() make Python3 happy.

### CODE REVIEW

**Comment by duncan-mccracken** [comment]
Hi @nmors,

This will need to reviewed with all the implementations of python2 that are in the supported operating systems, before it can be merged.

Currently support for Ubuntu 18 is only experimental, and as such, code specifically for making python3 happy may potentially break all the supported operating systems.

Duncan

**Comment by nmors** [comment]
@duncan-mccracken print with parentheses is also supported on python2 fyi.

Anyway, I'm going to run with my fork and continue testing on python 3. There are a few other things that need changing. I'll make sure that I don't break support for python 2

Thanks.

Another alternative is to modify the installation script for ubuntu 18.04 to install python2 instead of python3

**Comment by duncan-mccracken** [comment]
Also be aware that reposado is added verbatim from the upstream repo, so customising any of the SUS functionality will potentially get messy as the reposado code would need to be modified every time its revised.

**Comment by nmors** [comment]
I'll see how it goes for me for a while. If it turns out to be more trouble than what it's worth, I'll just roll back to python2

**Pull request closed without merging**
