### PR TITLE
Update SUS

### PR DESCRIPTION
**Pull request by Kaikon**
## New
- Target OS Version for a product (pic.1)
- Add link to download each package of update in the pop-up details (pic.2)
- (Optional) Enable filters based on update category (pic.3). This option can be enabled from SUS Settings (pic.4)

#### Pic.1
sus_tables_info

#### Pic.2
sus_product_details

#### Pic.3
sus_table_filters

#### Pic.4
sus_settings_filter

### CODE REVIEW

**Comment by wegotoeleven** [comment]
@Kaikon This looks killer. I'd change the "Target OS Version" title however to `macOS` in place of `Mac OSx`.

@duncan-mccracken Can we pull this in?

**Comment by duncan-mccracken** [comment]
Hi guys, sorry for the radio silence. Kinda thought this was a dead project, given all of Apple's deprecations.
@Kaikon I'm happy to merge this if the pull is updated according to @wegotoeleven's request.

**Review by duncan-mccracken — CHANGES_REQUESTED** [review]
Change Mac OSx references to macOS and we're good to go.

**Comment by Kaikon** [comment]
@wegotoeleven Thank's for your comment I have change all "Mac OSx" titles to "macOS"
@duncan-mccracken If no others changes is needed you can merge I think ?

**Pull request merged**
